{
  description = "Elixir development environment with mix2nix for reproducible builds";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs =
    {
      nixpkgs,
      flake-utils,
      ...
    }:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = nixpkgs.legacyPackages.${system};

        # Elixir version (can be changed to elixir_1_16, elixir_1_15, etc.)
        beamPackages = pkgs.beam.packages.erlang;
        inherit (beamPackages) elixir;

        # Build Elixir application using mix2nix
        # First run: mix2nix > mix.nix (generates dependency manifest)
        # Then use the generated mix.nix for reproducible builds
        buildMixProject =
          {
            pname,
            version,
            src,
            mixEnv ? "prod",
            mixNix ? ./mix.nix,
            ...
          }@args:
          let
            # Load dependencies from mix.nix (generated by mix2nix)
            # NOTE(pre-existing): mix.nix imports with `{ beamPackages }` only. If a future
            # mix2nix version requires a `lib` arg, add `inherit (pkgs) lib;` here.
            mixDeps = if builtins.pathExists mixNix then import mixNix { inherit beamPackages; } else [ ];
          in
          beamPackages.mixRelease (
            {
              inherit
                pname
                version
                src
                mixEnv
                ;

              # Dependencies from mix.nix
              inherit mixDeps;

              # Don't fetch deps at build time (use mixDeps instead)
              removeMixDeps = false;

              meta = with pkgs.lib; {
                description = "Elixir application built with Mix and mix2nix";
                platforms = platforms.unix;
              };
            }
            // builtins.removeAttrs args [
              "pname"
              "version"
              "src"
              "mixNix"
            ]
          );
      in
      rec {
        packages = {
          # Build the application as a release
          default = buildMixProject {
            pname = "auth_canary";
            version = "0.1.0";
            src = ./.;
            mixEnv = "prod";
            mixNix = ./mix.nix;
            # TODO(auth_canary-yxg.3): fetchGit overrides for git-sourced deps
            # These two deps are fetched from GitHub and require network access
            # in the Nix sandbox. Fix by adding fetchGit overrides via
            # beamPackages.fetchMixDep or mixFodDeps once SHAs are confirmed.
            #
            # spiffe_ex:
            #   owner = "QuentinMallet"; repo = "spiffe-ex";
            #   rev = "093352d98152718f9b5060c6c1e4fe3533c916f9";
            #
            # observlib:
            #   owner = "ForgottenBeast"; repo = "observlib-ex";
            #   rev = "f611dc2fd869675c4af806796c5afaadba4964ec";
          };

          # E2E test environment launcher (wraps process-compose)
          e2e-env = pkgs.writeShellScriptBin "e2e-env" ''
            exec ${pkgs.process-compose}/bin/process-compose up \
              -f ${toString ./.}/test/e2e/process-compose.yaml "$@"
          '';

          # Build documentation
          docs = pkgs.stdenv.mkDerivation {
            name = "elixir-app-docs";
            src = ./.;

            nativeBuildInputs = [
              elixir
              pkgs.git
            ];

            buildPhase = ''
              export MIX_HOME="$TMPDIR/.mix"
              export HEX_HOME="$TMPDIR/.hex"

              mix local.hex --force
              mix local.rebar --force
              mix deps.get
              mix docs
            '';

            installPhase = ''
              mkdir -p $out
              cp -r doc $out/
            '';
          };

          # Utility to generate mix.nix from mix.lock
          # Run: nix run .#generate-mix-nix
          generate-mix-nix = pkgs.writeShellScriptBin "generate-mix-nix" ''
            if [ ! -f mix.lock ]; then
              echo "Error: mix.lock not found. Run 'mix deps.get' first."
              exit 1
            fi

            echo "Generating mix.nix from mix.lock..."
            ${pkgs.mix2nix}/bin/mix2nix > mix.nix
            echo "✓ Generated mix.nix"
            echo ""
            echo "Next steps:"
            echo "  1. Commit mix.nix to version control"
            echo "  2. Uncomment 'mixNix = ./mix.nix;' in flake.nix packages.default"
            echo "  3. Run 'nix build' to build with locked dependencies"
          '';
        };

        # E2E test environment shell with all service dependencies
        devShells.e2e = pkgs.mkShell {
          buildInputs = with pkgs; [
            openbao
            spire
            zitadel # nixpkgs unstable 2.71.7 — confirmed available
            postgresql_16
            process-compose
            jq
            curl
            elixir
            erlang
            beamPackages.hex
            beamPackages.rebar3
            mix2nix
          ];
          shellHook = ''
            export MIX_HOME="$PWD/.nix-mix"
            export HEX_HOME="$PWD/.nix-hex"
            mkdir -p "$MIX_HOME" "$HEX_HOME"
            export PATH="$MIX_HOME/bin:$HEX_HOME/bin:$PATH"
            export LANG=C.UTF-8
            export LC_ALL=C.UTF-8
            echo "E2E test environment shell"
          '';
        };

        # Development shell with Elixir tools
        devShells.default = pkgs.mkShell {
          buildInputs = with pkgs; [
            # Elixir and Erlang
            elixir
            erlang

            # Hex and Rebar (required for dependencies, including GitHub repos)
            beamPackages.hex
            beamPackages.rebar3

            # mix2nix for generating mix.nix
            mix2nix

            # Development tools
            elixir-ls # Language server for IDE support
            git

            # Database clients (optional, uncomment if needed)
            # postgresql
            # sqlite

            # Additional tools
            inotify-tools # For file watching (Phoenix live reload)
          ];

          shellHook = ''
            # Set up Mix directories
            export MIX_HOME="$PWD/.nix-mix"
            export HEX_HOME="$PWD/.nix-hex"
            mkdir -p "$MIX_HOME" "$HEX_HOME"

            # Add Mix binaries to PATH
            export PATH="$MIX_HOME/bin:$HEX_HOME/bin:$PATH"

            # Locale settings for Elixir
            export LANG=C.UTF-8
            export LC_ALL=C.UTF-8

            echo "🧪 Elixir Development Environment (with mix2nix)"
            echo "=============================================="
            echo ""
            echo "Elixir version: $(elixir --version | head -1)"
            echo "Erlang/OTP: $(erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().' -noshell)"
            echo ""
            echo "Quick commands:"
            echo "  mix new <name>           - Create new Mix project"
            echo "  mix deps.get             - Fetch dependencies"
            echo "  mix compile              - Compile project"
            echo "  mix test                 - Run tests"
            echo "  mix test --cover         - Run tests with coverage"
            echo "  mix format               - Format code"
            echo "  mix credo                - Run static code analysis"
            echo "  mix credo --strict       - Run strict analysis"
            echo "  mix dialyzer             - Run type checker"
            echo "  mix release              - Build release"
            echo "  iex -S mix               - Start interactive shell"
            echo ""
            echo "mix2nix workflow:"
            echo "  mix2nix > mix.nix        - Generate mix.nix from mix.lock"
            echo "  nix run .#generate-mix-nix - Helper script to generate mix.nix"
            echo ""
            echo "Phoenix commands (if using Phoenix):"
            echo "  mix phx.new <name>       - Create Phoenix project"
            echo "  mix phx.server           - Start Phoenix server"
            echo "  mix ecto.create          - Create database"
            echo "  mix ecto.migrate         - Run migrations"
            echo ""
            echo "GitHub dependencies:"
            echo "  Add to mix.exs: {:dep, github: \"user/repo\"}"
            echo "  Then run: mix deps.get"
            echo ""
            echo "After adding/updating dependencies:"
            echo "  1. mix deps.get          - Fetch new dependencies"
            echo "  2. mix2nix > mix.nix     - Update Nix dependency manifest"
            echo "  3. git add mix.nix       - Commit updated manifest"
          '';
        };

        # App for running the built release
        apps = {
          default = flake-utils.lib.mkApp {
            drv = packages.default;
          };

          # Utility app to generate mix.nix
          generate-mix-nix = flake-utils.lib.mkApp {
            drv = packages.generate-mix-nix;
          };

          # E2E test environment launcher
          e2e-env = flake-utils.lib.mkApp {
            drv = packages.e2e-env;
          };
        };
      }
    );
}
